import { useState } from 'react';

export default function CrowdPage() {
  const [inflowSurge, setInflowSurge] = useState(1.0);
  const [station, setStation] = useState('MAS');
  const [incident, setIncident] = useState('NONE');

  return (
    <section className="page-view active" id="page-crowd">
      <div className="view-header">
        <div className="view-title-group">
          <div className="eyebrow"><span className="sys-num">SYSTEM 07</span> <span className="slash">//</span> CROWD FOOTPRINT &amp; SANDBOX</div>
          <div className="view-subtitle">
            <span className="pulse-dot"></span>
            SIMULATED MODEL
          </div>
          <h1 className="view-title">Platform Crowd Footprint Monitoring</h1>
          <p className="view-desc">
            Multi-platform density comparison, bottleneck detection, and simulated operational concurrency telemetry generated on a 3,000 ms background scheduler.
          </p>
        </div>
        <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
          <select 
            value={station}
            onChange={e => setStation(e.target.value)}
            style={{ padding: '8px 12px', background: 'rgba(14,20,36,0.8)', border: '1px solid var(--color-border-subtle)', borderRadius: 'var(--radius-sm)', color: '#fff', fontSize: '13px' }}
          >
            <option value="MAS">Chennai Central (MAS)</option>
            <option value="NDLS">New Delhi (NDLS)</option>
            <option value="CSMT">Mumbai CSMT</option>
            <option value="HWH">Howrah Jn (HWH)</option>
          </select>
          <button className="btn btn-secondary">Interval: 3,000 ms</button>
          <button className="btn btn-secondary">Audio: ON</button>
          <span className="badge badge-real">Tick #1</span>
        </div>
      </div>

      <div className="provenance-card provenance-banner" style={{ background: 'var(--color-surface)', padding: '16px', borderRadius: 'var(--radius-lg)', border: '1px solid var(--color-border-subtle)', borderLeft: '4px solid var(--color-cyan-400)', display: 'flex', gap: '16px', alignItems: 'flex-start', marginBottom: '24px' }}>
        <svg className="provenance-icon" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="var(--color-cyan-400)" strokeWidth="2">
          <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
        </svg>
        <div className="provenance-text" style={{ fontSize: '13px', color: 'var(--color-text-secondary)', lineHeight: 1.5 }}>
          <div className="provenance-title" style={{ fontWeight: 600, color: 'var(--color-text-primary)', marginBottom: '4px' }}>Data Provenance Guarantee</div>
          Crowd telemetry is generated by <code>CrowdSimulationService</code> using a 3,000 ms background scheduler. Station Registry &amp; Timetables are REAL DATA backed by SQLite. Rule Engine: <strong style={{ color: 'var(--color-status-emerald)' }}>&lt; 70% NORMAL</strong>, <strong style={{ color: '#f59e0b' }}>70%–89% WARNING</strong>, <strong style={{ color: '#ef4444' }}>&ge; 90% CRITICAL</strong>.
        </div>
      </div>

      <div className="panel" style={{ background: 'var(--color-surface)', borderRadius: 'var(--radius-lg)', border: '1px solid var(--color-border-subtle)', marginBottom: '24px' }}>
        <div className="panel-header" style={{ padding: '16px', borderBottom: '1px solid var(--color-border-subtle)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <span className="panel-title" style={{ fontWeight: 600, marginRight: '8px' }}>{station} — Terminal Platform Density Telemetry</span>
            <span className="badge badge-simulated">LIVE TICKING</span>
          </div>
          <span style={{ fontSize: '12px', color: 'var(--color-text-muted)' }}>Updated: Just now</span>
        </div>
        <div className="panel-body" style={{ padding: '24px' }}>
          {/* Mock Heatmap Grid */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '16px' }}>
            {[1, 2, 3, 4, 5, 6].map(pf => {
              const occupancy = Math.floor(Math.random() * (95 - 20) + 20);
              const status = occupancy > 90 ? 'CRITICAL' : (occupancy > 70 ? 'WARNING' : 'NORMAL');
              const color = status === 'CRITICAL' ? '#ef4444' : (status === 'WARNING' ? '#f59e0b' : 'var(--color-status-emerald)');
              return (
                <div key={pf} style={{ padding: '16px', background: 'rgba(14,20,36,0.5)', border: `1px solid ${color}`, borderRadius: 'var(--radius-md)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '12px' }}>
                    <span style={{ fontWeight: 600, color: '#fff' }}>Platform {pf}</span>
                    <span style={{ fontSize: '12px', color, fontWeight: 600 }}>{status}</span>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'baseline', gap: '8px', marginBottom: '12px' }}>
                    <span style={{ fontSize: '24px', fontFamily: 'var(--font-mono)', color: '#fff' }}>{occupancy}%</span>
                    <span style={{ fontSize: '12px', color: 'var(--color-text-muted)' }}>Load</span>
                  </div>
                  <div style={{ height: '6px', background: 'rgba(255,255,255,0.1)', borderRadius: '3px', overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: `${occupancy}%`, background: color }} />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      <div className="sandbox-panel" style={{ background: 'var(--color-surface)', borderRadius: 'var(--radius-lg)', border: '1px solid var(--color-border-subtle)' }}>
        <div className="sandbox-header" style={{ padding: '16px', borderBottom: '1px solid var(--color-border-subtle)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <span className="badge badge-derived" style={{ marginBottom: '8px', display: 'inline-block' }}>MODULE D • CASCADE STRESS ENGINE</span>
            <h3 style={{ margin: '0 0 4px 0', fontSize: '18px', fontWeight: 600 }}>"What-If" Cascade Stress-Test Sandbox</h3>
            <p style={{ margin: 0, fontSize: '13px', color: 'var(--color-text-secondary)' }}>Simulate high-volume passenger influx, delayed express rakes, and vertical infrastructure chokepoints.</p>
          </div>
          <span className="badge badge-real">SANDBOX ACTIVE</span>
        </div>
        <div className="sandbox-controls-grid" style={{ padding: '24px', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '24px', alignItems: 'end' }}>
          <div className="sandbox-field" style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            <label style={{ fontSize: '12px', color: 'var(--color-text-secondary)' }}>Inflow Surge Multiplier: <span style={{ color: 'var(--color-cyan-400)', fontWeight: 600 }}>{inflowSurge.toFixed(1)}x</span></label>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', color: 'var(--color-text-muted)', fontSize: '12px' }}>
              <span>1x</span>
              <input 
                type="range" 
                min="1.0" 
                max="5.0" 
                step="0.5" 
                value={inflowSurge}
                onChange={e => setInflowSurge(parseFloat(e.target.value))}
                style={{ flex: 1 }}
              />
              <span>5x</span>
            </div>
          </div>
          
          <div className="sandbox-field" style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            <label style={{ fontSize: '12px', color: 'var(--color-text-secondary)' }}>Inject Infrastructure Incident</label>
            <select 
              value={incident}
              onChange={e => setIncident(e.target.value)}
              style={{ padding: '10px 12px', background: 'rgba(14,20,36,0.8)', border: '1px solid var(--color-border-subtle)', borderRadius: 'var(--radius-sm)', color: '#fff', fontSize: '13px' }}
            >
              <option value="NONE">None (Nominal Operations)</option>
              <option value="FOB_BREAKDOWN">FOB 1 Escalator Breakdown (+45% Surge)</option>
              <option value="TRAIN_DELAY">Express Train 45m Delay (Pf 2 Overlap)</option>
              <option value="SIGNAL_FAULT">Platform 3 Signal Fault (Reroute Required)</option>
              <option value="FESTIVAL_RUSH">Diwali / Pongal Mass Influx (3.5x Multiplier)</option>
            </select>
          </div>

          <div style={{ display: 'flex', gap: '8px' }}>
            <button className="btn btn-primary" style={{ flex: 1, padding: '10px 16px', fontWeight: 600 }}>⏩ Fast-Forward</button>
            <button className="btn btn-secondary" style={{ padding: '10px 16px' }}>Reset</button>
          </div>
        </div>
      </div>
    </section>
  );
}
