/**
 * MockPnrProvider — Deterministic test provider for PNR status
 * Returns structured demo data based on PNR digit patterns
 */
const PnrProvider = require('./PnrProvider');

const SAMPLE_TRAINS = [
    { number: '12301', name: 'Howrah Rajdhani Express', from: 'NDLS', to: 'HWH', fromName: 'New Delhi', toName: 'Howrah Jn' },
    { number: '12951', name: 'Mumbai Rajdhani Express', from: 'MMCT', to: 'NDLS', fromName: 'Mumbai Central', toName: 'New Delhi' },
    { number: '12627', name: 'Karnataka Express', from: 'NDLS', to: 'SBC', fromName: 'New Delhi', toName: 'Bengaluru City' },
    { number: '12621', name: 'Tamil Nadu Express', from: 'NDLS', to: 'MAS', fromName: 'New Delhi', toName: 'Chennai Central' },
    { number: '12259', name: 'Sealdah Duronto Express', from: 'NDLS', to: 'SDAH', fromName: 'New Delhi', toName: 'Sealdah' },
    { number: '12002', name: 'Bhopal Shatabdi Express', from: 'NDLS', to: 'BPL', fromName: 'New Delhi', toName: 'Bhopal Jn' },
    { number: '12723', name: 'Telangana Express', from: 'NDLS', to: 'SC', fromName: 'New Delhi', toName: 'Secunderabad Jn' },
    { number: '12431', name: 'Thiruvananthapuram Rajdhani', from: 'NDLS', to: 'TVC', fromName: 'New Delhi', toName: 'Thiruvananthapuram' },
];

const STATUSES = ['CNF', 'RAC', 'WL', 'CNF', 'CNF', 'CNF'];
const CLASSES = ['1A', '2A', '3A', 'SL', '2S'];

class MockPnrProvider extends PnrProvider {
    constructor() {
        super('MockPnrProvider');
    }

    isAvailable() {
        return true;
    }

    async checkStatus(pnr) {
        // Simulate network latency
        await new Promise(r => setTimeout(r, 200 + Math.random() * 300));

        // Deterministic selection based on PNR digits
        const seed = parseInt(pnr.substring(0, 4));
        const train = SAMPLE_TRAINS[seed % SAMPLE_TRAINS.length];
        const passengerCount = (parseInt(pnr[5]) % 4) + 1;
        const classIdx = parseInt(pnr[6]) % CLASSES.length;

        const passengers = [];
        for (let i = 1; i <= passengerCount; i++) {
            const statusIdx = (parseInt(pnr[7 + (i % 3)]) + i) % STATUSES.length;
            const bookingStatus = STATUSES[statusIdx];
            let currentStatus = bookingStatus;

            // Some WL passengers may get confirmed
            if (bookingStatus === 'WL') {
                currentStatus = Math.random() > 0.4 ? 'RAC' : 'WL';
            }

            passengers.push({
                number: i,
                booking_status: bookingStatus === 'WL' ? `WL/${Math.floor(Math.random() * 50) + 1}` : bookingStatus,
                current_status: currentStatus === 'WL' ? `WL/${Math.floor(Math.random() * 30) + 1}` : currentStatus,
                coach: currentStatus === 'CNF' ? `${CLASSES[classIdx]}${Math.floor(Math.random() * 8) + 1}` : '--',
                berth: currentStatus === 'CNF' ? Math.floor(Math.random() * 72) + 1 : 0,
                berth_type: currentStatus === 'CNF' ? ['LB', 'MB', 'UB', 'SL', 'SU'][Math.floor(Math.random() * 5)] : '--'
            });
        }

        // Generate boarding date (tomorrow or day after)
        const boardDate = new Date();
        boardDate.setDate(boardDate.getDate() + (parseInt(pnr[4]) % 3) + 1);

        return {
            pnr: pnr,
            train_number: train.number,
            train_name: train.name,
            boarding_date: boardDate.toISOString().split('T')[0],
            from_station: { code: train.from, name: train.fromName },
            to_station: { code: train.to, name: train.toName },
            class: CLASSES[classIdx],
            chart_prepared: Math.random() > 0.5,
            passengers: passengers,
            provider: 'mock',
            disclaimer: 'This is DEMO data generated by MockPnrProvider for testing purposes. No real PNR data is being accessed.'
        };
    }
}

module.exports = MockPnrProvider;
